id = "renx"
name = "Renx"
description = "The open source coding agent."
version = "1.14.41"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/renx"

[agent_servers.renx]
name = "Renx"
icon = "./icons/renx.svg"

[agent_servers.renx.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/renx/releases/download/v1.14.41/renx-darwin-arm64.zip"
cmd = "./renx"
args = ["acp"]

[agent_servers.renx.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/renx/releases/download/v1.14.41/renx-darwin-x64.zip"
cmd = "./renx"
args = ["acp"]

[agent_servers.renx.targets.linux-aarch64]
archive = "https://github.com/anomalyco/renx/releases/download/v1.14.41/renx-linux-arm64.tar.gz"
cmd = "./renx"
args = ["acp"]

[agent_servers.renx.targets.linux-x86_64]
archive = "https://github.com/anomalyco/renx/releases/download/v1.14.41/renx-linux-x64.tar.gz"
cmd = "./renx"
args = ["acp"]

[agent_servers.renx.targets.windows-x86_64]
archive = "https://github.com/anomalyco/renx/releases/download/v1.14.41/renx-windows-x64.zip"
cmd = "./renx.exe"
args = ["acp"]
