name: renx

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  renx:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /renx') ||
      startsWith(github.event.comment.body, '/renx')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run renx
        uses: anomalyco/renx/github@latest
        env:
          RENX_API_KEY: ${{ secrets.RENX_API_KEY }}
          RENX_PERMISSION: '{"bash": "deny"}'
        with:
          model: renx/claude-opus-4-5
